### ISSUE TITLE
Save container with volumes

### ISSUE THREAD

**Issue by y0no** [camandel/docker-django-wiki#2]
Hi,
The container seems to works really great but when I try to save "/testproject" by using a volume, the container refuse to start saying that "manage.py" doesn't exists.

Do you have any solution to handle this issue ? Do I need to modify the Dockerfile to handle volume ?

**Comment by camandel** [comment]
Hi,
if you want to use an external volume for /testproject you have to clone the repository or copy all the files inside testproject directory. For example:

```
git clone https://github.com/camandel/docker-django-wiki.git mydata
docker run -d -P -v /tmp/mydata/testproject:/testproject camandel/django-wiki
```

**Comment by epeld** [comment]
Hi!
Alternatively, could we host the `db.sqlite3`-file in a separate directory - say under `/data` so that we can mount a volume over just that path?

**Comment by camandel** [comment]
Hi,
yes, you are right. You can change db location into testproject.settings file to a new properly path as and mount a volume over it (default is BASE_DIR). The paths used are only for demo purpose.
