### ISSUE TITLE
Getting an "Invalid HTTP_HOST header" error

### ISSUE THREAD

**Issue by jwater7** [camandel/docker-django-wiki#4]
When I start it up, it gives me this output:

> Performing system checks...
> System check identified no issues (0 silenced).
> May 18, 2017 - 00:17:50
> Django version 1.10.7, using settings 'testproject.settings'
> Starting development server at http://0.0.0.0:8000/
> Quit the server with CONTROL-C.
> Invalid HTTP_HOST header: '192.168.99.100:32769'. You may need to add u'192.168.99.100' to ALLOWED_HOSTS.
> [18/May/2017 00:17:50] "GET / HTTP/1.1" 400 59420
> Invalid HTTP_HOST header: '192.168.99.100:32769'. You may need to add u'192.168.99.100' to ALLOWED_HOSTS.
> [18/May/2017 00:19:15] "GET / HTTP/1.1" 400 59420
> Invalid HTTP_HOST header: '192.168.99.100:32769'. You may need to add u'192.168.99.100' to ALLOWED_HOSTS.

Traceback:

> /usr/local/lib/python2.7/dist-packages/django/core/handlers/exception.py in inner 
> 42.            response = get_response(request)
>  ...
> 
> /usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py in _legacy_get_response 
> 244.            response = middleware_method(request)
>  ...
> 
> /usr/local/lib/python2.7/dist-packages/django/middleware/common.py in process_request 
> 57.        host = request.get_host()
>  ...
> 
> /usr/local/lib/python2.7/dist-packages/django/http/request.py in get_host 
> 113.            raise DisallowedHost(msg)
>  ...

**Comment by jwater7** [comment]
Just a followup note - not sure if the django version changed, but it says:

>  Changed in Django 1.10.3:
> 
> In older versions, ALLOWED_HOSTS wasn’t checked if DEBUG=True. This was also changed in Django 1.9.11 and 1.8.16 to prevent a DNS rebinding attack.

Maybe this is originally why DEBUG=True is set inside the settings, but no longer works for this purpose?


According to [SO](http://stackoverflow.com/questions/24857158/commanderror-you-must-set-settings-allowed-hosts-if-debug-is-false), doing this instead might fix it:
`ALLOWED_HOSTS = ['*']
`

**Comment by camandel** [comment]
Fixed in  643273b.Thanks
