### ISSUE TITLE
Tagging container stable build revisions

### ISSUE THREAD

**Issue by jwater7** [camandel/docker-django-wiki#5]
Right now, the only tag listed on hub is "latest":

> Tag Name Compressed Size Last Updated
> latest  76 MB  17 days ago

There are previous builds before the latest changes that would be nice to be able to pull:

> Status Actions Tag Created Last Updated
> Success latest 17 days ago 17 days ago
> ...
> Success   2 years ago 2 years ago

**Comment by camandel** [comment]
From this version a new tag will be added to keep the old builds.
